---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu-focal
    box: bento/ubuntu-20.04
    memory: 1024
    cpus: 2
    box_version: 202005.21.0
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  config_options:
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
