---
name: Test pt3_driver role
on:
  push:
    paths:
      - 'roles/pt3_driver/**'
      - 'Pipfile.lock'

env:
  python_version: 3.8
  pipenv_version: 2020.6.2
  role_dir: roles/pt3_driver

jobs:
  test_linux:
    strategy:
      matrix:
        scenario:
          - ubuntu-focal
          - ubuntu-bionic
          - centos-8
          - centos-7
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
      - name: Restore cache if available
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Restore pipenv cache if available
        uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
        with:
          version: ${{ env.pipenv_version }}
      - name: Install dependencies
        run: pipenv sync --dev
        env:
          PIP_EXISTS_ACTION: i
      - name: Run provisioning
        run: cd ${{ env.role_dir }} && pipenv run molecule test -s ${{ matrix.scenario }}
        timeout-minutes: 15
